// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/iskanye/mirea-queue/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) Get(ctx interface{}, key interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCache_Get_Call) Run(run func(ctx context.Context, key string)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(s string, err error) *MockCache_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCache
func (_mock *MockCache) Set(ctx context.Context, key string, val string) error {
	ret := _mock.Called(ctx, key, val)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, val)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
func (_e *MockCache_Expecter) Set(ctx interface{}, key interface{}, val interface{}) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", ctx, key, val)}
}

func (_c *MockCache_Set_Call) Run(run func(ctx context.Context, key string, val string)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_Set_Call) Return(err error) *MockCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(ctx context.Context, key string, val string) error) *MockCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockQueue
func (_mock *MockQueue) Clear(ctx context.Context, queue models.Queue) error {
	ret := _mock.Called(ctx, queue)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue) error); ok {
		r0 = returnFunc(ctx, queue)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockQueue_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
func (_e *MockQueue_Expecter) Clear(ctx interface{}, queue interface{}) *MockQueue_Clear_Call {
	return &MockQueue_Clear_Call{Call: _e.mock.On("Clear", ctx, queue)}
}

func (_c *MockQueue_Clear_Call) Run(run func(ctx context.Context, queue models.Queue)) *MockQueue_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Clear_Call) Return(err error) *MockQueue_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Clear_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue) error) *MockQueue_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Pop provides a mock function for the type MockQueue
func (_mock *MockQueue) Pop(ctx context.Context, queue models.Queue) (models.QueueEntry, error) {
	ret := _mock.Called(ctx, queue)

	if len(ret) == 0 {
		panic("no return value specified for Pop")
	}

	var r0 models.QueueEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue) (models.QueueEntry, error)); ok {
		return returnFunc(ctx, queue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue) models.QueueEntry); ok {
		r0 = returnFunc(ctx, queue)
	} else {
		r0 = ret.Get(0).(models.QueueEntry)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Queue) error); ok {
		r1 = returnFunc(ctx, queue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Pop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pop'
type MockQueue_Pop_Call struct {
	*mock.Call
}

// Pop is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
func (_e *MockQueue_Expecter) Pop(ctx interface{}, queue interface{}) *MockQueue_Pop_Call {
	return &MockQueue_Pop_Call{Call: _e.mock.On("Pop", ctx, queue)}
}

func (_c *MockQueue_Pop_Call) Run(run func(ctx context.Context, queue models.Queue)) *MockQueue_Pop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Pop_Call) Return(queueEntry models.QueueEntry, err error) *MockQueue_Pop_Call {
	_c.Call.Return(queueEntry, err)
	return _c
}

func (_c *MockQueue_Pop_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue) (models.QueueEntry, error)) *MockQueue_Pop_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockQueue
func (_mock *MockQueue) Push(ctx context.Context, queue models.Queue, entry models.QueueEntry) error {
	ret := _mock.Called(ctx, queue, entry)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue, models.QueueEntry) error); ok {
		r0 = returnFunc(ctx, queue, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockQueue_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
//   - entry models.QueueEntry
func (_e *MockQueue_Expecter) Push(ctx interface{}, queue interface{}, entry interface{}) *MockQueue_Push_Call {
	return &MockQueue_Push_Call{Call: _e.mock.On("Push", ctx, queue, entry)}
}

func (_c *MockQueue_Push_Call) Run(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry)) *MockQueue_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		var arg2 models.QueueEntry
		if args[2] != nil {
			arg2 = args[2].(models.QueueEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_Push_Call) Return(err error) *MockQueue_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Push_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry) error) *MockQueue_Push_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueViewer creates a new instance of MockQueueViewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueViewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueViewer {
	mock := &MockQueueViewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueViewer is an autogenerated mock type for the QueueViewer type
type MockQueueViewer struct {
	mock.Mock
}

type MockQueueViewer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueViewer) EXPECT() *MockQueueViewer_Expecter {
	return &MockQueueViewer_Expecter{mock: &_m.Mock}
}

// Range provides a mock function for the type MockQueueViewer
func (_mock *MockQueueViewer) Range(ctx context.Context, queue models.Queue, n int64) ([]models.QueueEntry, error) {
	ret := _mock.Called(ctx, queue, n)

	if len(ret) == 0 {
		panic("no return value specified for Range")
	}

	var r0 []models.QueueEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue, int64) ([]models.QueueEntry, error)); ok {
		return returnFunc(ctx, queue, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue, int64) []models.QueueEntry); ok {
		r0 = returnFunc(ctx, queue, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.QueueEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Queue, int64) error); ok {
		r1 = returnFunc(ctx, queue, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueViewer_Range_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Range'
type MockQueueViewer_Range_Call struct {
	*mock.Call
}

// Range is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
//   - n int64
func (_e *MockQueueViewer_Expecter) Range(ctx interface{}, queue interface{}, n interface{}) *MockQueueViewer_Range_Call {
	return &MockQueueViewer_Range_Call{Call: _e.mock.On("Range", ctx, queue, n)}
}

func (_c *MockQueueViewer_Range_Call) Run(run func(ctx context.Context, queue models.Queue, n int64)) *MockQueueViewer_Range_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueViewer_Range_Call) Return(queueEntrys []models.QueueEntry, err error) *MockQueueViewer_Range_Call {
	_c.Call.Return(queueEntrys, err)
	return _c
}

func (_c *MockQueueViewer_Range_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue, n int64) ([]models.QueueEntry, error)) *MockQueueViewer_Range_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueuePosition creates a new instance of MockQueuePosition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueuePosition(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueuePosition {
	mock := &MockQueuePosition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueuePosition is an autogenerated mock type for the QueuePosition type
type MockQueuePosition struct {
	mock.Mock
}

type MockQueuePosition_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueuePosition) EXPECT() *MockQueuePosition_Expecter {
	return &MockQueuePosition_Expecter{mock: &_m.Mock}
}

// GetPosition provides a mock function for the type MockQueuePosition
func (_mock *MockQueuePosition) GetPosition(ctx context.Context, queue models.Queue, entry models.QueueEntry) (int64, error) {
	ret := _mock.Called(ctx, queue, entry)

	if len(ret) == 0 {
		panic("no return value specified for GetPosition")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue, models.QueueEntry) (int64, error)); ok {
		return returnFunc(ctx, queue, entry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue, models.QueueEntry) int64); ok {
		r0 = returnFunc(ctx, queue, entry)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Queue, models.QueueEntry) error); ok {
		r1 = returnFunc(ctx, queue, entry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueuePosition_GetPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosition'
type MockQueuePosition_GetPosition_Call struct {
	*mock.Call
}

// GetPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
//   - entry models.QueueEntry
func (_e *MockQueuePosition_Expecter) GetPosition(ctx interface{}, queue interface{}, entry interface{}) *MockQueuePosition_GetPosition_Call {
	return &MockQueuePosition_GetPosition_Call{Call: _e.mock.On("GetPosition", ctx, queue, entry)}
}

func (_c *MockQueuePosition_GetPosition_Call) Run(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry)) *MockQueuePosition_GetPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		var arg2 models.QueueEntry
		if args[2] != nil {
			arg2 = args[2].(models.QueueEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueuePosition_GetPosition_Call) Return(n int64, err error) *MockQueuePosition_GetPosition_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQueuePosition_GetPosition_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry) (int64, error)) *MockQueuePosition_GetPosition_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueLength creates a new instance of MockQueueLength. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueLength(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueLength {
	mock := &MockQueueLength{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueLength is an autogenerated mock type for the QueueLength type
type MockQueueLength struct {
	mock.Mock
}

type MockQueueLength_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueLength) EXPECT() *MockQueueLength_Expecter {
	return &MockQueueLength_Expecter{mock: &_m.Mock}
}

// Len provides a mock function for the type MockQueueLength
func (_mock *MockQueueLength) Len(ctx context.Context, queue models.Queue) (int64, error) {
	ret := _mock.Called(ctx, queue)

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue) (int64, error)); ok {
		return returnFunc(ctx, queue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue) int64); ok {
		r0 = returnFunc(ctx, queue)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Queue) error); ok {
		r1 = returnFunc(ctx, queue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueLength_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockQueueLength_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
func (_e *MockQueueLength_Expecter) Len(ctx interface{}, queue interface{}) *MockQueueLength_Len_Call {
	return &MockQueueLength_Len_Call{Call: _e.mock.On("Len", ctx, queue)}
}

func (_c *MockQueueLength_Len_Call) Run(run func(ctx context.Context, queue models.Queue)) *MockQueueLength_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueLength_Len_Call) Return(n int64, err error) *MockQueueLength_Len_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQueueLength_Len_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue) (int64, error)) *MockQueueLength_Len_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueSwap creates a new instance of MockQueueSwap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueSwap(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueSwap {
	mock := &MockQueueSwap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueSwap is an autogenerated mock type for the QueueSwap type
type MockQueueSwap struct {
	mock.Mock
}

type MockQueueSwap_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueSwap) EXPECT() *MockQueueSwap_Expecter {
	return &MockQueueSwap_Expecter{mock: &_m.Mock}
}

// LetAhead provides a mock function for the type MockQueueSwap
func (_mock *MockQueueSwap) LetAhead(ctx context.Context, queue models.Queue, entry models.QueueEntry) error {
	ret := _mock.Called(ctx, queue, entry)

	if len(ret) == 0 {
		panic("no return value specified for LetAhead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue, models.QueueEntry) error); ok {
		r0 = returnFunc(ctx, queue, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueSwap_LetAhead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LetAhead'
type MockQueueSwap_LetAhead_Call struct {
	*mock.Call
}

// LetAhead is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
//   - entry models.QueueEntry
func (_e *MockQueueSwap_Expecter) LetAhead(ctx interface{}, queue interface{}, entry interface{}) *MockQueueSwap_LetAhead_Call {
	return &MockQueueSwap_LetAhead_Call{Call: _e.mock.On("LetAhead", ctx, queue, entry)}
}

func (_c *MockQueueSwap_LetAhead_Call) Run(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry)) *MockQueueSwap_LetAhead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		var arg2 models.QueueEntry
		if args[2] != nil {
			arg2 = args[2].(models.QueueEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueSwap_LetAhead_Call) Return(err error) *MockQueueSwap_LetAhead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueSwap_LetAhead_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry) error) *MockQueueSwap_LetAhead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueRemover creates a new instance of MockQueueRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueRemover {
	mock := &MockQueueRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueRemover is an autogenerated mock type for the QueueRemover type
type MockQueueRemover struct {
	mock.Mock
}

type MockQueueRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueRemover) EXPECT() *MockQueueRemover_Expecter {
	return &MockQueueRemover_Expecter{mock: &_m.Mock}
}

// Remove provides a mock function for the type MockQueueRemover
func (_mock *MockQueueRemover) Remove(ctx context.Context, queue models.Queue, entry models.QueueEntry) error {
	ret := _mock.Called(ctx, queue, entry)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Queue, models.QueueEntry) error); ok {
		r0 = returnFunc(ctx, queue, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueRemover_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockQueueRemover_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - queue models.Queue
//   - entry models.QueueEntry
func (_e *MockQueueRemover_Expecter) Remove(ctx interface{}, queue interface{}, entry interface{}) *MockQueueRemover_Remove_Call {
	return &MockQueueRemover_Remove_Call{Call: _e.mock.On("Remove", ctx, queue, entry)}
}

func (_c *MockQueueRemover_Remove_Call) Run(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry)) *MockQueueRemover_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Queue
		if args[1] != nil {
			arg1 = args[1].(models.Queue)
		}
		var arg2 models.QueueEntry
		if args[2] != nil {
			arg2 = args[2].(models.QueueEntry)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueRemover_Remove_Call) Return(err error) *MockQueueRemover_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueRemover_Remove_Call) RunAndReturn(run func(ctx context.Context, queue models.Queue, entry models.QueueEntry) error) *MockQueueRemover_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupProvider creates a new instance of MockGroupProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupProvider {
	mock := &MockGroupProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupProvider is an autogenerated mock type for the GroupProvider type
type MockGroupProvider struct {
	mock.Mock
}

type MockGroupProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupProvider) EXPECT() *MockGroupProvider_Expecter {
	return &MockGroupProvider_Expecter{mock: &_m.Mock}
}

// GetGroups provides a mock function for the type MockGroupProvider
func (_mock *MockGroupProvider) GetGroups(ctx context.Context, group string, limit int) ([]models.Group, error) {
	ret := _mock.Called(ctx, group, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]models.Group, error)); ok {
		return returnFunc(ctx, group, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []models.Group); ok {
		r0 = returnFunc(ctx, group, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, group, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupProvider_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockGroupProvider_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - group string
//   - limit int
func (_e *MockGroupProvider_Expecter) GetGroups(ctx interface{}, group interface{}, limit interface{}) *MockGroupProvider_GetGroups_Call {
	return &MockGroupProvider_GetGroups_Call{Call: _e.mock.On("GetGroups", ctx, group, limit)}
}

func (_c *MockGroupProvider_GetGroups_Call) Run(run func(ctx context.Context, group string, limit int)) *MockGroupProvider_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupProvider_GetGroups_Call) Return(groups []models.Group, err error) *MockGroupProvider_GetGroups_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupProvider_GetGroups_Call) RunAndReturn(run func(ctx context.Context, group string, limit int) ([]models.Group, error)) *MockGroupProvider_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubjectsProvider creates a new instance of MockSubjectsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubjectsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubjectsProvider {
	mock := &MockSubjectsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubjectsProvider is an autogenerated mock type for the SubjectsProvider type
type MockSubjectsProvider struct {
	mock.Mock
}

type MockSubjectsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubjectsProvider) EXPECT() *MockSubjectsProvider_Expecter {
	return &MockSubjectsProvider_Expecter{mock: &_m.Mock}
}

// GetSubjects provides a mock function for the type MockSubjectsProvider
func (_mock *MockSubjectsProvider) GetSubjects(ctx context.Context, group models.Group) ([]string, error) {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for GetSubjects")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Group) ([]string, error)); ok {
		return returnFunc(ctx, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Group) []string); ok {
		r0 = returnFunc(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Group) error); ok {
		r1 = returnFunc(ctx, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubjectsProvider_GetSubjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubjects'
type MockSubjectsProvider_GetSubjects_Call struct {
	*mock.Call
}

// GetSubjects is a helper method to define mock.On call
//   - ctx context.Context
//   - group models.Group
func (_e *MockSubjectsProvider_Expecter) GetSubjects(ctx interface{}, group interface{}) *MockSubjectsProvider_GetSubjects_Call {
	return &MockSubjectsProvider_GetSubjects_Call{Call: _e.mock.On("GetSubjects", ctx, group)}
}

func (_c *MockSubjectsProvider_GetSubjects_Call) Run(run func(ctx context.Context, group models.Group)) *MockSubjectsProvider_GetSubjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Group
		if args[1] != nil {
			arg1 = args[1].(models.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubjectsProvider_GetSubjects_Call) Return(strings []string, err error) *MockSubjectsProvider_GetSubjects_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSubjectsProvider_GetSubjects_Call) RunAndReturn(run func(ctx context.Context, group models.Group) ([]string, error)) *MockSubjectsProvider_GetSubjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserCreator creates a new instance of MockUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCreator {
	mock := &MockUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCreator is an autogenerated mock type for the UserCreator type
type MockUserCreator struct {
	mock.Mock
}

type MockUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCreator) EXPECT() *MockUserCreator_Expecter {
	return &MockUserCreator_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserCreator
func (_mock *MockUserCreator) CreateUser(ctx context.Context, chatID int64, user models.User) error {
	ret := _mock.Called(ctx, chatID, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.User) error); ok {
		r0 = returnFunc(ctx, chatID, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCreator_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserCreator_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - user models.User
func (_e *MockUserCreator_Expecter) CreateUser(ctx interface{}, chatID interface{}, user interface{}) *MockUserCreator_CreateUser_Call {
	return &MockUserCreator_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, chatID, user)}
}

func (_c *MockUserCreator_CreateUser_Call) Run(run func(ctx context.Context, chatID int64, user models.User)) *MockUserCreator_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.User
		if args[2] != nil {
			arg2 = args[2].(models.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserCreator_CreateUser_Call) Return(err error) *MockUserCreator_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCreator_CreateUser_Call) RunAndReturn(run func(ctx context.Context, chatID int64, user models.User) error) *MockUserCreator_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRemover creates a new instance of MockUserRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRemover {
	mock := &MockUserRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRemover is an autogenerated mock type for the UserRemover type
type MockUserRemover struct {
	mock.Mock
}

type MockUserRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRemover) EXPECT() *MockUserRemover_Expecter {
	return &MockUserRemover_Expecter{mock: &_m.Mock}
}

// RemoveUser provides a mock function for the type MockUserRemover
func (_mock *MockUserRemover) RemoveUser(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRemover_RemoveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUser'
type MockUserRemover_RemoveUser_Call struct {
	*mock.Call
}

// RemoveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockUserRemover_Expecter) RemoveUser(ctx interface{}, chatID interface{}) *MockUserRemover_RemoveUser_Call {
	return &MockUserRemover_RemoveUser_Call{Call: _e.mock.On("RemoveUser", ctx, chatID)}
}

func (_c *MockUserRemover_RemoveUser_Call) Run(run func(ctx context.Context, chatID int64)) *MockUserRemover_RemoveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRemover_RemoveUser_Call) Return(err error) *MockUserRemover_RemoveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRemover_RemoveUser_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockUserRemover_RemoveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserModifier creates a new instance of MockUserModifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserModifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserModifier {
	mock := &MockUserModifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserModifier is an autogenerated mock type for the UserModifier type
type MockUserModifier struct {
	mock.Mock
}

type MockUserModifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserModifier) EXPECT() *MockUserModifier_Expecter {
	return &MockUserModifier_Expecter{mock: &_m.Mock}
}

// UpdateUser provides a mock function for the type MockUserModifier
func (_mock *MockUserModifier) UpdateUser(ctx context.Context, chatID int64, user models.User) error {
	ret := _mock.Called(ctx, chatID, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.User) error); ok {
		r0 = returnFunc(ctx, chatID, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserModifier_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserModifier_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - user models.User
func (_e *MockUserModifier_Expecter) UpdateUser(ctx interface{}, chatID interface{}, user interface{}) *MockUserModifier_UpdateUser_Call {
	return &MockUserModifier_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, chatID, user)}
}

func (_c *MockUserModifier_UpdateUser_Call) Run(run func(ctx context.Context, chatID int64, user models.User)) *MockUserModifier_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.User
		if args[2] != nil {
			arg2 = args[2].(models.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserModifier_UpdateUser_Call) Return(err error) *MockUserModifier_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserModifier_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, chatID int64, user models.User) error) *MockUserModifier_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) GetUser(ctx context.Context, chatID int64) (models.User, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (models.User, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) models.User); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserProvider_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockUserProvider_Expecter) GetUser(ctx interface{}, chatID interface{}) *MockUserProvider_GetUser_Call {
	return &MockUserProvider_GetUser_Call{Call: _e.mock.On("GetUser", ctx, chatID)}
}

func (_c *MockUserProvider_GetUser_Call) Run(run func(ctx context.Context, chatID int64)) *MockUserProvider_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_GetUser_Call) Return(user models.User, err error) *MockUserProvider_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_GetUser_Call) RunAndReturn(run func(ctx context.Context, chatID int64) (models.User, error)) *MockUserProvider_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
